remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin    : "mint"

# Site Settings
locale                   : "en-US"
title                    : "The Subtle Art of Waiting for Lunch"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Alex Herman"
description              : "A collection of posts and tutorials"
url                      : "https://alexherman2.github.io"
repository               : alexherman2/alexherman2.github.io
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : " "
words_per_minute         : 200

# Site Author
author:
  name             : "Alex Herman"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "DevOps engineer by way of software developer by way of mechanical engineer. I like REST APIs, automation pipelines, infrastructure as code, and pasta.
  location         : "Cleveland, Ohio"
  email            :
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://alexherman.net"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlexHerman2"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url:

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

