remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin    : "mint"

# Site Settings
locale                   : "en-US"
title                    : "The Subtle Art of Waiting for Lunch"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Alex Herman"
description              : "A collection of posts and tutorials"
url                      : "https://alexherman2.github.io"
repository               : alexherman2/alexherman2.github.io
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : " "
words_per_minute         : 200

# Site Author
author:
  name             : "Alex Herman"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "I'm a software developer in sunny Cleveland, Ohio. I work mostly with Java, Go, and Javascript but have been known to veer into Ruby and Python when the mood strikes. I've been running APIs and web apps in Kubernetes for several years now and can break nearly anything in strange and interesting ways. Currently working in health tech, but I was a mechanical engineer working with rubber products in a past life (and I still think tires are amazing pieces of technology).

  Husband to Haley, father to Piper, can opener to two cats. Infrequent social media user. Novice gardener. I don't claim to be an authority on anything I post here, but I relied on the work and knowledge of so many people over the years I feel like I should give some knowledge back. Hence, this blog."
  location         : "Cleveland, Ohio"
  email            :
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://alexherman.net"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/AlexHerman2"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

